branches:
    - .*
matrix:
    - env: MONKEBASE_CONNECTION=imonke@unix(/run/mysqld/mysqld.sock)/imonke FERROTHORN_HOST=http://localhost:4000 FERROTHORN_SECRET=secret
      image: golang:latest-mysql
    - env: MONKEBASE_CONNECTION=imonke@unix(/run/mysqld/mysqld.sock)/imonke FERROTHORN_HOST=http://localhost:4000 FERROTHORN_SECRET=secret
      image: golang:1.15-mysql
    - env: MONKEBASE_CONNECTION=imonke@unix(/run/mysqld/mysqld.sock)/imonke FERROTHORN_HOST=http://localhost:4000 FERROTHORN_SECRET=secret
      image: golang:1.14-mysql
    - env: MONKEBASE_CONNECTION=imonke@unix(/run/mysqld/mysqld.sock)/imonke FERROTHORN_HOST=http://localhost:4000 FERROTHORN_SECRET=secret
      image: golang:1.13-mysql
before_script:
    - sudo service mysql start
    - sudo mysql -uroot -e"CREATE DATABASE imonke; CREATE USER 'imonke'@'localhost'; GRANT ALL PRIVILEGES ON imonke.* TO 'imonke'@'localhost';"
    - sudo apt-get update
    - sudo apt-get install -y lsof
    - go run ./cmd/ferrothorn_mock/main.go&
script:
    - go test ./... -cover -count 1
after_script:
    - kill $(lsof -i :4000 -sTCP:LISTEN |awk 'NR > 1 {printf $2}') || echo "ferrothorn mock not running"
