version: "3"

services:
    mongo:
        image: mongo
        container_name: ferro-mongo
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=ferrothorn
    ferrothorn:
        image: gastrodon/ferro
        ports:
            - 8000:80
        environment:
            - FERRO_MONGO_HOST=ferro-mongo
            - FERRO_MONGO_USER=root
            - FERRO_MONGO_PASS=ferrothorn
            - FERRO_MONGO_BASE=ferrothorn
            - FERRO_LOG_LEVEL=0
